language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"

# commands to install dependencies
install:
  - "python -m pip install -U pip"
  - "python -m pip install -e ."

# commands to run tests
script:
  - python -c "import Levenshtein"
  - "python setup.py test"
